// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SyscallReadArgs struct {
	_   structs.HostLayout
	Buf uint64
	Fd  int32
	_   [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SyscallMapEvents             = "events"
	SyscallMapReadStash          = "read_stash"
	SyscallProgTraceEnterClose   = "trace_enter_close"
	SyscallProgTraceEnterConnect = "trace_enter_connect"
	SyscallProgTraceEnterRead    = "trace_enter_read"
	SyscallProgTraceEnterWrite   = "trace_enter_write"
	SyscallProgTraceExitRead     = "trace_exit_read"
	SyscallVarTargetPid          = "target_pid"
)

// LoadSyscall returns the embedded CollectionSpec for Syscall.
func LoadSyscall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Syscall: %w", err)
	}

	return spec, err
}

// LoadSyscallObjects loads Syscall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SyscallObjects
//	*SyscallPrograms
//	*SyscallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSyscallObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSyscall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SyscallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallSpecs struct {
	SyscallProgramSpecs
	SyscallMapSpecs
	SyscallVariableSpecs
}

// SyscallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallProgramSpecs struct {
	TraceEnterClose   *ebpf.ProgramSpec `ebpf:"trace_enter_close"`
	TraceEnterConnect *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
	TraceEnterRead    *ebpf.ProgramSpec `ebpf:"trace_enter_read"`
	TraceEnterWrite   *ebpf.ProgramSpec `ebpf:"trace_enter_write"`
	TraceExitRead     *ebpf.ProgramSpec `ebpf:"trace_exit_read"`
}

// SyscallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallMapSpecs struct {
	Events    *ebpf.MapSpec `ebpf:"events"`
	ReadStash *ebpf.MapSpec `ebpf:"read_stash"`
}

// SyscallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// SyscallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallObjects struct {
	SyscallPrograms
	SyscallMaps
	SyscallVariables
}

func (o *SyscallObjects) Close() error {
	return _SyscallClose(
		&o.SyscallPrograms,
		&o.SyscallMaps,
	)
}

// SyscallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallMaps struct {
	Events    *ebpf.Map `ebpf:"events"`
	ReadStash *ebpf.Map `ebpf:"read_stash"`
}

func (m *SyscallMaps) Close() error {
	return _SyscallClose(
		m.Events,
		m.ReadStash,
	)
}

// SyscallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// SyscallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallPrograms struct {
	TraceEnterClose   *ebpf.Program `ebpf:"trace_enter_close"`
	TraceEnterConnect *ebpf.Program `ebpf:"trace_enter_connect"`
	TraceEnterRead    *ebpf.Program `ebpf:"trace_enter_read"`
	TraceEnterWrite   *ebpf.Program `ebpf:"trace_enter_write"`
	TraceExitRead     *ebpf.Program `ebpf:"trace_exit_read"`
}

func (p *SyscallPrograms) Close() error {
	return _SyscallClose(
		p.TraceEnterClose,
		p.TraceEnterConnect,
		p.TraceEnterRead,
		p.TraceEnterWrite,
		p.TraceExitRead,
	)
}

func _SyscallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscall_bpfel.o
var _SyscallBytes []byte
