// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SyscallMapEvents             = "events"
	SyscallProgTraceEnterConnect = "trace_enter_connect"
)

// LoadSyscall returns the embedded CollectionSpec for Syscall.
func LoadSyscall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SyscallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Syscall: %w", err)
	}

	return spec, err
}

// LoadSyscallObjects loads Syscall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SyscallObjects
//	*SyscallPrograms
//	*SyscallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSyscallObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSyscall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SyscallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallSpecs struct {
	SyscallProgramSpecs
	SyscallMapSpecs
	SyscallVariableSpecs
}

// SyscallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallProgramSpecs struct {
	TraceEnterConnect *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
}

// SyscallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// SyscallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SyscallVariableSpecs struct {
}

// SyscallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallObjects struct {
	SyscallPrograms
	SyscallMaps
	SyscallVariables
}

func (o *SyscallObjects) Close() error {
	return _SyscallClose(
		&o.SyscallPrograms,
		&o.SyscallMaps,
	)
}

// SyscallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *SyscallMaps) Close() error {
	return _SyscallClose(
		m.Events,
	)
}

// SyscallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallVariables struct {
}

// SyscallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSyscallObjects or ebpf.CollectionSpec.LoadAndAssign.
type SyscallPrograms struct {
	TraceEnterConnect *ebpf.Program `ebpf:"trace_enter_connect"`
}

func (p *SyscallPrograms) Close() error {
	return _SyscallClose(
		p.TraceEnterConnect,
	)
}

func _SyscallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed syscall_bpfeb.o
var _SyscallBytes []byte
