// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TlsSslReadArgs struct {
	_   structs.HostLayout
	Ssl uint64
	Buf uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TlsMapEvents             = "events"
	TlsMapSslReadStash       = "ssl_read_stash"
	TlsProgTraceSslReadEnter = "trace_ssl_read_enter"
	TlsProgTraceSslReadExit  = "trace_ssl_read_exit"
	TlsProgTraceSslWrite     = "trace_ssl_write"
	TlsVarTargetPid          = "target_pid"
)

// LoadTls returns the embedded CollectionSpec for Tls.
func LoadTls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tls: %w", err)
	}

	return spec, err
}

// LoadTlsObjects loads Tls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TlsObjects
//	*TlsPrograms
//	*TlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTlsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsSpecs struct {
	TlsProgramSpecs
	TlsMapSpecs
	TlsVariableSpecs
}

// TlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsProgramSpecs struct {
	TraceSslReadEnter *ebpf.ProgramSpec `ebpf:"trace_ssl_read_enter"`
	TraceSslReadExit  *ebpf.ProgramSpec `ebpf:"trace_ssl_read_exit"`
	TraceSslWrite     *ebpf.ProgramSpec `ebpf:"trace_ssl_write"`
}

// TlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	SslReadStash *ebpf.MapSpec `ebpf:"ssl_read_stash"`
}

// TlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TlsVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// TlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsObjects struct {
	TlsPrograms
	TlsMaps
	TlsVariables
}

func (o *TlsObjects) Close() error {
	return _TlsClose(
		&o.TlsPrograms,
		&o.TlsMaps,
	)
}

// TlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	SslReadStash *ebpf.Map `ebpf:"ssl_read_stash"`
}

func (m *TlsMaps) Close() error {
	return _TlsClose(
		m.Events,
		m.SslReadStash,
	)
}

// TlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// TlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TlsPrograms struct {
	TraceSslReadEnter *ebpf.Program `ebpf:"trace_ssl_read_enter"`
	TraceSslReadExit  *ebpf.Program `ebpf:"trace_ssl_read_exit"`
	TraceSslWrite     *ebpf.Program `ebpf:"trace_ssl_write"`
}

func (p *TlsPrograms) Close() error {
	return _TlsClose(
		p.TraceSslReadEnter,
		p.TraceSslReadExit,
		p.TraceSslWrite,
	)
}

func _TlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tls_bpfeb.o
var _TlsBytes []byte
